tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - muhammad-sammy.csharp@1.23.9:BMArOoGwWqKRrH6s4E2/AQ==